Anzeige wins
michael-mezgo/the-coding-memory pull request #11
Opened 2022-12-28 21:52 UTC by elimei1

Hab die "win" anzeige hinzugefügt. Hab viele verschieden Sachen probiert, nachdem allerdings nichts so wirklich hingehaut hat, bin ich bei der originalen Version geblieben und hab nur die Schriftart etwas verändert, sodass es besser lesbar ist. Die wirkliche Anzahl an wins kann noch nicht angezeigt werden, weil uns dazu eine Methode fehlt, die einen win erkennt. Wir nutzen derzeit den score des Spielers ja noch nichtmal. Maybe kann sich Leo das anschauen wenn er Zeit hat?

2022-12-28 22:18 UTC, Nour-hash commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/GameViewController.java
Finde die ich gut, hast du gut umgesetzt und schnell (daumen nach hoch :) )

2022-12-28 22:21 UTC, Nour-hash commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/PlayGame.java
>              if (cardOpendByCurrentplayer) {
Ist das einfach die game logik, die die Karten offen lässt oder schließt und wenn ja hat das nicht leo gemacht. Nur eine Frage verbessere mich gerne, wenn ich falsch liege ;)

2022-12-28 22:22 UTC, Nour-hash approved these changes

2022-12-29 11:09 UTC, elimei1 commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/PlayGame.java
>              if (cardOpendByCurrentplayer) {
Ja hat eh Leo gemacht, hab nur etwas probiert um das mit dem score zu lösen. Hab wohl irgendwas verschoben deswegen wird angezeigt, dass ich das erstellt hab. Ist aber alles von Leo

2022-12-29 17:34 UTC, michael-mezgo requested changes
Hi, danke für die schnelle Umsetzung 🔝.
Gefällt mir ganz gut, hab bei einigen Sachen meinen Senf dazugegeben, weil ich mir gedacht hab, dass wir über diese Designentscheidungen / Ideen diskutieren könnten. Diese müssen nicht alle umgesetzt werden.

---

Das einzige, was ich wirklich gerne ändern würde wäre, dass das Player-Objekt verwendet wird, da wir dann auch die Namen nutzen können.

2022-12-29 17:34 UTC, michael-mezgo commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/PlayGame.java
>              if (cardOpendByCurrentplayer) {
Denke das ist die automatische Formatierung von IntelliJ.

2022-12-29 17:34 UTC, michael-mezgo commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/GameViewController.java
> +            BorderPane.setMargin(grid, new Insets(0, 70, 250, 0));
Ich müsste selbst nach einer Möglichkeit suchen, aber mir gefallen diese absoluten Werte nicht ganz, da es dann auf jedem Bildschirm anders ist - bzw. im unwahrscheinlichen Extremfall bei ganz schlechter Auflösung gar nicht angezeigt wird. - Leider habe ich bisher noch nichts über die Einheiten der Insets gefunden.

@Nour-hash das wäre eventuell ein finaler Task für uns, dass wir schauen, dass wir solche Sachen auch responsive bekommen. Das war ja auch bei meinen Task ein Stein im Weg.

2022-12-29 17:34 UTC, michael-mezgo commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/GameViewController.java
> +            BorderPane.setMargin(grid, new Insets(0, 0, 10, 0));
siehe oberer Kommentar

2022-12-29 17:34 UTC, michael-mezgo commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/GameViewController.java
> +        Label player1Label = new Label("Player 1 wins: ");
Wäre es hier eventuell nicht schöner ein Player-Objekt von @EP1210 mitzugeben und aus diesem die Wins auszulesen?

Das IncreaseScore sollte @c2210475031 dann noch in der Spiellogik umsetzen.
```Java
        Label player1Label = new Label(Player1.getName() + " wins: " + Player1.getScore());
```

2022-12-29 17:34 UTC, michael-mezgo commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/GameViewController.java
> +        Label player2Label = new Label("Player 2 wins:");
siehe Player 1

2022-12-29 17:34 UTC, michael-mezgo commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/GameViewController.java
> +    public void displayWinStatus(int player1Wins, int player2Wins) {
Ich denke, dass es hier einfacher wäre das Grid und Labels als Objektvariable anzulegen.

Dann wäre es möglich, kleinere Methoden zu bauen (z.B. Initialize [Text erstellen, UI-Objekte anlegen]; Update [neue Werte eintragen]) usw.

2022-12-29 21:51 UTC, elimei1 commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/GameViewController.java
> +        Label player1Label = new Label("Player 1 wins: ");
Wenn ich das so umsetze, dann startet das Spiel nicht. Weil zu Beginn die Namen noch mit null deklariert sind. Hast du eine Idee, wie wir das umgehen können?

2022-12-29 22:13 UTC, michael-mezgo commented on memory-fx/src/main/java/com/fhcampuswien/project/memoryfx/GameViewController.java
> +        Label player1Label = new Label("Player 1 wins: ");
Am besten erstell folgende Methode:
```Java
        private void initializeGame() {…}
```

Von dort aus rufen wir deine Methode auf. Der Initializer wird im EventHandler von @EP1210 (Drücken des Buttons) aufgerufen. 

Diese zusätzliche Methode möchte ich aus dem Grund machen, da ich das Spielbrett dann auch erst erstellen möchte, wenn die Spieler bereits angelegt wurden. Und aus Gründen der Lesbarkeit würde ich das in dieses initializeGame geben.

- - -

Wenn wir dann das Objekt haben, können wir das automatische Update eventuell auch über ein Binding lösen. Diesen Task würde dann allerdings ich übernehmen, da ich da erst auch selbst recherchieren muss.
Somit brauchen wir deine Methode nur für die Initialisierung. Somit würde das Update automatisch passieren und @c2210475031 muss in seiner Spiellogik nur das increaseScore beachten.

2022-12-30 10:37 UTC, michael-mezgo approved these changes
Nach persönlichen Gespräch passt es nun :). Mündliches OK

2022-12-30 11:05 UTC, merged